#!/bin/sh -x
# scripts for the maintainer (whose initials are 'nsd')

case $1 in
  configure)
    # rebuild configure and *.in after changing configure.ac
    aclocal && autoheader && automake && autoconf && ./configure --enable-debug
    exit $?
    ;;
  prep)
    # configure and make distclean
    $0 configure
    make clean
    if ! make check; then
     exit 1
    fi
    make distclean
    rm -rf autom4te.cache
    ;;
  recompile)
    # upload and recompile on each of the sourceforge compile farm servers
    TGZ=pwsafe.tgz
    tar czvf /tmp/$TGZ .
    scp /tmp/$TGZ ndade@cf-shell.sourceforge.net:$TGZ
    rm /tmp/$TGZ

    # some hosts need custom stuff passed in to ./configure
    ppc_osx1_conf="--without-readline --with-openssl-dir=/sw"
    ppc_osx2_conf="--without-readline"
    sparc_solaris1_conf="--without-readline"
    x86_freebsd1_make=gmake
    x86_netbsd1_conf="--without-readline --without-x"
    x86_netbsd1_make=gmake
    x86_openbsd1_make=gmake
 
    for host in alpha-linux1 amd64-linux1 ppc-osx1 ppc-osx2 sparc-solaris1 x86-freebsd1 x86-linux1 x86-linux2 x86-netbsd1 x86-openbsd1; do
      RSH="ssh -l`echo $USER|tr -d -` cf-shell.sourceforge.net ssh $host"
      DIR=$host
      CONF="`echo $host|tr -- - _`_conf"
      MAKE="`echo $host|tr -- - _`_make"
      if $RSH "rm -rf $DIR \; \
            mkdir -p $DIR \; \
            gunzip <$TGZ | tar xvf - -C $DIR" ; then
        if $RSH "cd $DIR \; ./configure ${!CONF-}"; then
          $RSH "cd $DIR \; ${!MAKE-make} check"
        fi
      fi
    done
    ;;
  compile)
    # prep & recompile combined
    $0 prep
    $0 recompile
    ;;
  release)
    # tar up a release
    VER=`awk <configure.ac '/^AM_INIT_AUTOMAKE/ { print $2 }' | tr -d ')'`
    TGZ=pwsafe-$VER.tar.gz
    DIR=pwsafe-$VER
    rm -rf ../$DIR
    ( cd ..; cvs -d `cat pwsafe/CVS/Root` export -d $DIR -D tomorrow pwsafe; )
    ( cd ../$DIR; ./nsd prep; )
    tar czvf ../$TGZ -C ../ $DIR
    # and make the archival copy
    ( cd ../$DIR; ./configure --program-suffix=$VER; make; strip pwsafe; )
    ;;
  *)
    echo "Usage $0 (configure|prep|compile|recompile|release)"
    exit 1
esac


